version: "3.8"

services:
  backend:
    build: ./backend
    container_name: tasks-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: tasks_frontend
    ports:
      - "3000:80"
    networks:
      - webnet

networks:
  webnet:
